version: "3"
services:
  client-bot:
    container_name: catalog_client_bot
    build: ./client-bot
    restart: unless-stopped
    networks:
      - catalog
  admin-bot:
    container_name: catalog_admin_bot
    build: ./admin-bot
    restart: unless-stopped
    networks:
      - catalog 
  tg1-bot:
    container_name: tg1_bot
    build: ./tgbot1
    restart: unless-stopped
    networks:
      - catalog
  tg2-bot:
    container_name: tg2_bot
    build: ./tgbot2
    restart: unless-stopped
    networks:
      - catalog    
  strapi:
    container_name: catalog_strapi
    platform: linux/amd64 #for platform error on Apple M1 chips
    build: ./strapi
    image: strapi:latest
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_CLIENT: sqlite
      DATABASE_NAME: /usr/src/api/data.db
    volumes:
      - ./strapi/config:/opt/app/config
      - ./strapi/src:/opt/app/src
      - ./strapi/package.json:/opt/package.json
      - ./strapi/yarn.lock:/opt/yarn.lock
      - ./strapi/.env:/opt/app/.env
      - ./strapi/public/uploads:/opt/app/public/uploads
    ports:
      - "1337:1337"
    networks:
      - catalog
    command: yarn develop  

networks:
  catalog:
